// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AutoSubmitController from "./auto_submit_controller"
application.register("auto-submit", AutoSubmitController)

import ConfirmDialogController from "./confirm_dialog_controller"
application.register("confirm-dialog", ConfirmDialogController)

import DialogController from "./dialog_controller"
application.register("dialog", DialogController)

import DropdownSearchController from "./dropdown_search_controller"
application.register("dropdown-search", DropdownSearchController)

import FilterController from "./filter_controller"
application.register("filter", FilterController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import HintController from "./hint_controller"
application.register("hint", HintController)

import NotificationController from "./notification_controller"
application.register("notification", NotificationController)

import PasswordVisibilityController from "./password_visibility_controller"
application.register("password-visibility", PasswordVisibilityController)

import RecordLimitSelectorController from "./record_limit_selector_controller"
application.register("record-limit-selector", RecordLimitSelectorController)
